### ISSUE TITLE
why can't compile the project in windows7 or linux？

### ISSUE THREAD

**Issue by alyen028** [thiagopnts/kaleidoscope#15]
Hi thiagopnts：
     why can't compile the project in windows7 or linux？
     Thanks!

**Comment by alyen028** [comment]
Hi Thiago:
    npm version: windows - 3.8.9; linux - 3.8.3。
    now, update clappr-video360 to latest version@0.0.3, it's Ok！
    thanks very much！






在 2017-01-02 07:42:22，"Thiago Pontes" <notifications@github.com> 写道：


Reopened #15.

**Comment by thiagopnts** [comment]
cool thanks!

**Comment by alyen028** [comment]
Hi thiagopnts:
    compile is ok now, but it has an another question:
    it plays a cool.mp4 right(has video and audio) on clappr-video360 version@0.0.2, update to latest version@0.0.3, play only has audio but no video.
    browser: chrome version 54.0.2840.99 m , firefox 50.0.2.
    Look forward to your reply, thanks !
    
     





在 2017-01-03 10:41:01，"Thiago Pontes" <notifications@github.com> 写道：


cool thanks!

**Comment by thiagopnts** [comment]
Hey @alyen028, do you any errors on the browser console?

**Comment by alyen028** [comment]
Hi thiagopnts:
    the browser console log info:
        1、version@0.0.2, play ok：has video and audio
                    
        clappr-video360.min.js:9 The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
        clappr-video360.min.js:7 WebGL: INVALID_VALUE: texImage2D: no video
        test.html?mode=1&type=vr:1 [.Offscreen-For-WebGL-0C66A490]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
            
         2、version@0.0.3, play error：has audio but no video
        
              
        clappr-video360.min.js:9 The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
        clappr-video360.min.js:7 WebGL: INVALID_VALUE: texImage2D: no video
        test.html?mode=1&type=vr:1 [.Offscreen-For-WebGL-0CF8C878]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.




At 2017-01-03 23:56:50, "Thiago Pontes" <notifications@github.com> wrote:


Hey @alyen028, do you any errors on the browser console?

**Comment by thiagopnts** [comment]
hmm these are all non-fatal warnings, are you running the index page on a web server?

**Comment by alyen028** [comment]
hmm,  i run the index page on a web server.


At 2017-01-05 04:29:28, "Thiago Pontes" <notifications@github.com> wrote:


hmm these are all non-fatal warnings, are you running the index page on a web server?

**Comment by thiagopnts** [comment]
@alyen028 weird, I'll open another issue to try to track this

**Comment by thiagopnts** [comment]
So, you're testing with [clappr-video360](https://github.com/thiagopnts/clappr-video360) right?
I opened https://github.com/thiagopnts/clappr-video360/issues/10 there, you can update the issue there with any other info you might have

**Comment by alyen028** [comment]
hi thiagopnts:
    It's my fault. i pass error param of width and height, problem is now ok.
    but now i have another problem:
          it play on ios10+, it has no video but has audio.






At 2017-01-07 00:38:01, "Thiago Pontes" <notifications@github.com> wrote:


So, you're testing with clappr-video360 right?
I opened thiagopnts/clappr-video360#10 there, you can update the issue there with any other info you might have
