### ISSUE TITLE
HLS suport

### ISSUE THREAD

**Issue by FernandoJBCosta** [thiagopnts/kaleidoscope#16]
Hello Thiago does support HLS m3u8 files?

Best regards and have a fantastic 2017.

**Comment by thiagopnts** [comment]
Hello! yes it does, but you need to prepare the video tag first. Using hls.js would be something like this:
```js
var video = document.getElementById("videotag");
var hls = new Hls();
hls.loadSource('http://www.streambox.fr/playlists/test_001/stream.m3u8');
hls.attachMedia(video);
var viewer = new Kaleidoscope.Video({source: video, containerId: '#target'});
viewer.render();
```

**Comment by FernandoJBCosta** [comment]
Hello Thiago thanks for the replay but gives me this error:

253teste.html:1 [.Offscreen-For-WebGL-000001F16CD475E0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
teste.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.

Any help?

Best regards

**Comment by thiagopnts** [comment]
Weird, I'll create an examples folder in the project with some setups and this as well

**Comment by thiagopnts** [comment]
also, which OS/browser you tested?

**Comment by FernandoJBCosta** [comment]
Hello Thiago I test it in all principal browsers + iOS and Android.
I think its better you see for your self and you can test it:
I prepared an VPS with nginx and rtmp2hls module so you can test it.

CONNECT SSH: **52.174.159.206**
USER: **adminplay**
PASS: **1234567890.play**

the web files are at **/usr/local/nginx/html/**
you can stream to **rtmp://52.174.159.206:1935/live/test**, and the hls file will be genarated on **/usr/local/nginx/html/hls/test.m3u8**

link to website: **http://52.174.159.206/index.html**
link to hls file: **http://52.174.159.206/hls/test.m3u8**

Best regards
Fernando Jorge

**Comment by thiagopnts** [comment]
Hi, I'll be adding an `examples` folder in the project with some working examples with hls and dash. In the meantime, I would suggest you to change the credentials you posted(and avoid doing this!)

**Comment by FernandoJBCosta** [comment]
Ok thanks and sorry the server I created just for testing propose, best regards

**Comment by thiagopnts** [comment]
I added an HLS example here: https://github.com/thiagopnts/kaleidoscope/blob/master/examples/hls.html which you can see here: thiago.me/kaleidoscope/examples/hls.html
If it doesn't work with your m3u8 I would suggest you to first try to play for hls stream with HLS.js first to validate
