### ISSUE TITLE
Progressive example not playing in Iphone 6

### ISSUE THREAD

**Issue by yarandoo** [thiagopnts/kaleidoscope#17]
Hi, 

Trying the following example in Safari IOs 10.2.1:

> http://thiago.me/kaleidoscope/examples/mp4

I found that the video is not playing, although an initial image is displayed and moving the phone does move the image in 360. Also the touch functionality works to scroll through the sphere.

I believe the issue is related to IOs autoplay policies. As a video is only allowed to autoplay if it contains no audio tracks or if it is muted. See: 
> https://webkit.org/blog/6784/new-video-policies-for-ios/

Should this example be updated by adding a start button like in:
> http://thiago.me/kaleidoscope/

?

I can submit a PR if you agree.

Cheers,

**Comment by thiagopnts** [comment]
Hi @yarandoo, yeah you're right! I would be glad if you send a PR to fix this, but instead of the button, I would like to keep it fullscreen and play on tap anywhere on the screen

**Comment by yarandoo** [comment]
Perfect, I will have a look today and keep you posted. Cheers.

**Comment by yarandoo** [comment]
Thiago, I think it would be nice to replace the hosted sample under your domain as the link in the readme still lacks the new functionality. Are you thinking to update it? Cheers

**Comment by thiagopnts** [comment]
Thats my bad, I forgot the examples are in https://github.com/thiagopnts/thiagopnts.github.com
I will delete it from there and publish this repo as a gh-page, thanks!

**Comment by yarandoo** [comment]
Yes, but consider that the ios sample wont work unless you also push the sample video to the repo to serve it from the same domain as ghpage.

**Comment by thiagopnts** [comment]
Yeah, they are in different repos but all under the thiago.me domain, the only ones that are outside of it are the hls and dash examples, I'll add a note on these on the readme mentioning this, thanks!
