### ISSUE TITLE
valid for product images?

### ISSUE THREAD

**Issue by jujes** [thiagopnts/kaleidoscope#19]
Hi, is possible use Kaleidoscope for product, as reel.js?
thanks in advance,

**Comment by thiagopnts** [comment]
Hi @jujes, do you have an example?

**Comment by jujes** [comment]
hi @thiagopnts 
yes, here:
http://www.djangopaths.com/interactive-360-degree-product-views-wagtail-streamfield-block/

looking for use image product rotation on saleor (django based)

**Comment by thiagopnts** [comment]
oh I see what you mean. No, we dont support group of images, only equirectangular images

**Comment by jujes** [comment]
ok, thanks! :)
