### ISSUE TITLE
360 image from local directory not loading.

### ISSUE THREAD

**Issue by semosem** [thiagopnts/kaleidoscope#22]
Hello Thiago!

Great work! image works fine when loading the source from external link but not from the local folder. I couldn't fix it and it has been three hours now.

------WORKS FINE------

    var viewer = new Kaleidoscope.Image({
        **source: 'http://thiago.me/image-360/Polie_Academy_53.JPG',**

    });

----- DOESN'T WORK-------

    var viewer = new Kaleidoscope.Image({
        **source: 'Polie_Academy_53.JPG',**

    });

**Comment by thiagopnts** [comment]
hey, did you find the problem?

**Comment by semosem** [comment]
Hey there@thiagopnts

Thanks for the response. It was a CORS blocking error. I manage to solve it. 

Thanks 🙏  again
