### ISSUE TITLE
WebVR Support

### ISSUE THREAD

**Issue by flavioribeiro** [thiagopnts/kaleidoscope#26]
Do you think it's worth it to add a WebVR mode for cardboards? refs https://github.com/googlevr/webvr-polyfill

**Comment by newtoncalegari** [comment]
+1

I've been using it in a project and there's a demand for VR mode.
Would be happy to contribute to this.

**Comment by thiagopnts** [comment]
I dont have any plans to implement VR support now, mostly to avoid bloat(e.g. the webvr-polyfill size is more than half of this lib's size). For VR I would suggest using google's vrview: https://github.com/googlevr/vrview
