### ISSUE TITLE
Question: Video style 360 viewer?

### ISSUE THREAD

**Issue by ewb-git** [thiagopnts/kaleidoscope#27]
Sorry to ask you this, but I've been looking at all these totally outdated 360 product spin viewers.

The concept is a little different, but how hard would it be to say, record a product spinning as a video, and then use something like kaleidoscope to pan/spin the video frames of the product. Sort of like a 360 product spin, but from video rather than jpgs/pngs/gif images. Would be really cool o.o;;

Hope you don't mind me posting this here.
Thanks : )

**Comment by thiagopnts** [comment]
Hello, no problem! You mean something like this? http://www.djangopaths.com/interactive-360-degree-product-views-wagtail-streamfield-block/
we don't have plans to support this format, only equirectangular images

**Comment by ewb-git** [comment]
I mean sort of like this. I looked through maybe 100 options for various 360 viewers/players, but like the one you linked, they all load jpgs/pngs, for example use 32 jpegs to rotate, it's fairly common.

I was thinking more along the lines of what you are using, that would be like to take a video of a product spinning on a table, and then have the ability to play the video and drag it like in Kaleidoscope to do the 360.

Thanks for the reply, honestly wasn't thinking I'd get one. Good luck on the project!
