### ISSUE TITLE
How to free old Kaleidoscope object?

### ISSUE THREAD

**Issue by soharang** [thiagopnts/kaleidoscope#29]
Thank you for providing this great plug-in.

I am making a gallery with 360 vr pics so I added following function.
`<script>
function loadImage(img_src, yaw){
 	document.getElementById("container360").innerHTML = "";
 	var viewer = new Kaleidoscope.Image({
           source: img_src,
           containerId: '#container360',
           height:600, width:1280,
           initialYaw:yaw 	    
        });
      viewer.render();
     window.onresize = function() {
 		viewer.setSize({height: 600, width: 1280});
     }; } 
</script>`

And I called it with <a> tag as bellow.
```
<a href="javascript:loadImage('a.jpg', 270);" attr-a="onclick : attr-a">aaa</a><br/>
<a href="javascript:loadImage('b.jpg', 270);" attr-a="onclick : attr-a">bbb</a><br/>
```

The problem is that after several loading my links, my system got very slow for huge memory usage.

Anyone can help me to free memory allocated by new Kaleidoscope objects?

**Comment by thiagopnts** [comment]
Hello, you can call `viewer.destroy()` it will release all the resources. I noticed this is not on the docs, I'll add now.
Thanks!

**Comment by soharang** [comment]
Hello,
Thanks for your quick support and it really word well!
