### ISSUE TITLE
Is there any way to capture video end event?

### ISSUE THREAD

**Issue by dsushmasagar** [thiagopnts/kaleidoscope#30]
I tried the following code to capture video end event. But it didn't workout. Is there any way to capture "Video End" event. Basically I am trying to render video initial state when video is done.

document.querySelector(containerSelector).addEventListener('ended', viewer.play.bind(viewer));

**Comment by thiagopnts** [comment]
You can do `viewer.element.addEventListerner('ended', () => console.log('video ended'));`
`viewer.element` is the current `<video>` tag being rendered

**Comment by dsushmasagar** [comment]
@thiagopnts, Thank you so much, it's worked.  I had one more question,  I tried to enable video controls on video element using below code. but it din't worked.
      **viewer.element.controls = true;**
is there any way we can enable video controls?

**Comment by thiagopnts** [comment]
Hello @dsushmasagar, its not possible to see the controls because the video tag is always hidden, what you see on the screen is a canvas tag. For controls you would need to build your own(using the video tag events/methods)
