### ISSUE TITLE
Start/Stop Gyroscope navigation

### ISSUE THREAD

**Issue by its2loud** [thiagopnts/kaleidoscope#32]
Is it possible to switch gyroscope movement on or off on mobile devices?

**Comment by thiagopnts** [comment]
No, you would need to remove the event listener e add it again to enable

**Comment by its2loud** [comment]
could you give a short hint how to do that?

**Comment by thiagopnts** [comment]
Hello, you can do something like this:
```js
// to stop the gyro movement
window.removeEventListener('devicemotion', viewer.controls.onDeviceMotion);
// to start it again
window.addEventListener('devicemotion', viewer.controls.onDeviceMotion);
```

**Comment by thiagopnts** [comment]
closing this, let me know if you have any problems
