### ISSUE TITLE
Is there a way to pan the 360 images automatically after render?

### ISSUE THREAD

**Issue by mjpattani** [thiagopnts/kaleidoscope#34]
I want a feature where the image scrolls horizontally on its own. auto pan option like the autoplay option for video

**Comment by thiagopnts** [comment]
Hi, you can implement this on your side with:

```
requestAnimationFrame(function loop() {
    viewer.controls.theta += 0.005;
    requestAnimationFrame(loop)
});
```
and increase/decrease the speed by changing the `0.005` value

**Comment by mjpattani** [comment]
thank you. this works great.
