### ISSUE TITLE
Can i stop the autopan 360 image view after clicking anywhere on the viewer?

### ISSUE THREAD

**Issue by siddharthsinh** [thiagopnts/kaleidoscope#37]

**Comment by siddharthsinh** [comment]
i wants the Stop automatically move pan image after onMouseDown event?

**Comment by siddharthsinh** [comment]
i want to do like this example

**Comment by thiagopnts** [comment]
you can do the pan this way: https://github.com/thiagopnts/kaleidoscope/issues/34
to stop on click you could listen to a click event on the canvas and call `cancelAnimationFrame(loop)` to stop it

**Comment by siddharthsinh** [comment]
can i get the degree of pan image after the moving manually?

**Comment by thiagopnts** [comment]
yes, being x the vertical and y the horizontal, you can get the degree of each with `viewer.controls.phi` and `viewer.controls.theta` respectively. the value is in radians, so you need to convert with something like `const degrees = viewer.controls.theta * 180 / Math.PI`

**Comment by siddharthsinh** [comment]
Got it, thank you so much
