### ISSUE TITLE
Gyro doesn't work on Android (Chrome 65+)

### ISSUE THREAD

**Issue by SteveEdson** [thiagopnts/kaleidoscope#39]
Apparently Chrome 65 changed the way that this works, and broke a few things in the process. Details have been documented here:

https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3

TLDR:

> In Chrome m65, a regression to devicemotion events doesn't provide rotationRate, breaking the head tracking in the polyfill, and m66 switching DeviceMotionEvent.rotationRate values to use degrees instead of radians to be aligned with the spec.

**Chrome 65 - Android (Current stable)**
No motion at all

**Chrome 66 - Android (Current beta)** 
**Chrome 68 - Android (Current canary)**
Really sensitive motion, unusable, due to new units being used

**Comment by Scaalees** [comment]
Here's a video showing the issue:

https://youtu.be/IifGHhUmUbo

This is happening and both Chrome and Firefox on Android devices.

**Comment by twfarnam** [comment]
Hey, it looks like Kaleidoscope is already expecting degrees from the event. It's using a three.js function to adapt them in [controls.js](https://github.com/thiagopnts/kaleidoscope/blob/2cf1f4a1af9475bf08994b430140102c946947ed/src/controls.js#L118-L119):

    let alpha = THREE.Math.degToRad(event.rotationRate.alpha);
    let beta = THREE.Math.degToRad(event.rotationRate.beta);

I found that changing this hard-coded value in [line 15](https://github.com/thiagopnts/kaleidoscope/blob/2cf1f4a1af9475bf08994b430140102c946947ed/src/controls.js#L15) of the same file fixed the issue for me: 

    this.velo = (utils.isiOS() || utils.isEdge()) ? 0.02 : 1.6;

I changed it to the below and now it feels very natural again:

    this.velo = 0.02;

**Comment by howtomake** [comment]
++

**Comment by thiagopnts** [comment]
I updated this on master but I dont an android device to test, anyone can take a look? also check firefox if possible

**Comment by thiagopnts** [comment]
I finally got an android device to tests these things, I'll have an update soon

**Comment by thiagopnts** [comment]
this should be fixed now
