### ISSUE TITLE
How can I determine whether the browser supports

### ISSUE THREAD

**Issue by dblate** [thiagopnts/kaleidoscope#40]
Hi, is there w way to determine whether the browser supports?
If the browser can't render 360 video, so I can tell the user.
But I didn't found a  method like isSupported.
Is there a way I can do this?

Thanks!

**Comment by thiagopnts** [comment]
Hi @dblate, in theory the browser only has to support WebGL in order for this to work, so you would need to [check for WebGL support](https://developer.mozilla.org/en-US/docs/Learn/WebGL/By_example/Detect_WebGL)

**Comment by dblate** [comment]
Thanks a lot!
em.. I found that on my iphone, safari and chrome work fine. But in most app's webview(for example wechat and baidubox), the [example](http://thiago.me/kaleidoscope/examples/mp4) just stay black(they support WebGL), they won't play the video and won't trigger onError callback.
That confused me

**Comment by thiagopnts** [comment]
hmm, that's weird. Is that an android or iOS webview? I see it working on facebook webview on iOS. Also, did you try to tap the black screen to see if it starts to play? IIRC the autoplay support on webviews defaults to false

**Comment by dblate** [comment]
My environment is IOS 10.3 iphone6s, and we use WeChat, also I tapped the black screen, but nothing happened.

**Comment by dblate** [comment]
My environment is IOS 10.3 iphone6s, and we use WeChat, also I tapped the black screen, but nothing happened.
It's hard to debug in webview, since you have not encountered this situation, maybe I should not bother you in a long time.
