### ISSUE TITLE
Multiple render

### ISSUE THREAD

**Issue by xeux** [thiagopnts/kaleidoscope#42]
Looking for a way to render multiple containers, possibly by selecting using the div class, or a jQuery each, any docs in how to achieve this? It is possible?

**Comment by thiagopnts** [comment]
you can do this by creating different instances for each container, e.g.:
```js
var viewer1 = new Kaleidoscope.Video({source: 'equirectangular-video1.mp4', containerId: '#container1'});
viewer1.render();

var viewer2 = new Kaleidoscope.Video({source: 'equirectangular-video2.mp4', containerId: '#container2'});
viewer2.render();

// other container instances

```

**Comment by thiagopnts** [comment]
Closing this, let me know if you have any other issues!
