### ISSUE TITLE
How to  control through device motion - using gyroscope

### ISSUE THREAD

**Issue by swapnildubal** [thiagopnts/kaleidoscope#43]
I want to have the device motion effect on the image. Currently the code looks like:
var viewer = new Kaleidoscope.Image({
      source: myImage, 
      containerId: '#target',
      height: window.innerHeight,
      width: window.innerWidth
    });
    viewer.render();

Not sure which property do I need to pass to enable the gyroscope.

**Comment by markoakden** [comment]
This worked for me -
window.addEventListener('devicemotion', viewer.controls.onDeviceMotion);

**Comment by thiagopnts** [comment]
interesting, in theory we already handle that by default. Are you loading the image inside an iframe?

**Comment by markoakden** [comment]
No iframe, I added a switch to my app to allow the device motion to be switched on/off by the user. I discovered that to stop the device motion handler:

window.removeEventListener('devicemotion', viewer.controls.onDeviceMotion);

So, to start it again:

window.addEventListener('devicemotion', viewer.controls.onDeviceMotion);

As you say, the default seems to be on.

Great piece of code by the way!

**Comment by thiagopnts** [comment]
aah yeah makes sense, I thought it wasnt working on the first load. Thanks, glad it worked for you!

**Comment by swapnildubal** [comment]
@thiagopnts The gyroscope is working when I deployed the App to heroku. But it doesn't work when I tried to test it on my cellphone connected to my laptop (via IP address). Not sure why.

Also, is there any way we could show compass or lat-long on the image?
Thanks

**Comment by thiagopnts** [comment]
@swapnildubal you're testing on ios or android? and are you getting any errors or just the gyro stops working?

For the compass, you would have to implement one yourself, but it should be easy to do that with CSS using the values from `viewer.controls.theta` and `viewer.controls.phi`

**Comment by swapnildubal** [comment]
Both - android and ios.

Will check `viewer.controls.theta` and `viewer.controls.phi` this, if you have a codesandbox url handy please do share.

**Comment by thiagopnts** [comment]
do you see any errors? are the images coming from the same domain?

I wrote this awhile back:
https://codepen.io/thiagopnts/pen/zVdEZvk
from your code you will want to calculate the right degrees from theta and phi and update the `.fov` class with `rotate(Xdeg)` where X is the result from theta and phi, IIRC theta and phi values are in radians, you'll have to convert to degrees

**Comment by swapnildubal** [comment]
Gyroscope works only on https protocol, hence it was not working on localhost :).

It's working now. Will check the codepen.

Thanks @thiagopnts

**Comment by swapnildubal** [comment]
Issue is resolved and hence closing it.

**Comment by thiagopnts** [comment]
👍
