### ISSUE TITLE
latest version of the package is not available on npm

### ISSUE THREAD

**Issue by ghost** [thiagopnts/kaleidoscope#46]
are you sure you publish latest version with scoped name? i've just updated clappr-video360, that uses @thiagopnts/kaleidoscope, and yarn can not resolve latest version of this package from registry.

**Comment by thiagopnts** [comment]
Hey sorry for that, the @thiagopnts/kaleidoscope is published on the github package registry and kaleidoscopejs on npm, and apparently the github registry doesnt play well with yarn yet: https://github.com/yarnpkg/yarn/issues/7552
I published a new version of clappr-video360(v0.1.1) that uses kaleidoscopejs from npm, so it should work for you again

**Comment by ghost** [comment]
thanks👍
