### ISSUE TITLE
Please provide an example

### ISSUE THREAD

**Issue by TranceGeniK** [thiagopnts/kaleidoscope#6]
Hi!

I'm looking for a 360 video player with ios and deviceorientation compatibility. Is this one working?
Can you please provide an example?

Thanks !

**Comment by thiagopnts** [comment]
Hey, this is still a working in progress, and yes, I plan to support these features. I might have a working release next weekend, once I have it in place I'll add instructions about how to use!

**Comment by TranceGeniK** [comment]
Great, thanks !

**Comment by thiagopnts** [comment]
I started to add some info here https://github.com/thiagopnts/kaleidoscope/blob/master/README.md
